apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: mltru-com
data:
  vector.yaml: |
    sources:
      nginx_logs:
        type: file
        include:
          - /var/log/nginx/access.log

    transforms:
      parse_json:
        type: remap
        inputs: ["nginx_logs"]
        source: |
          parsed = parse_json!(.message)
          .timestamp = parsed.time_local
          .body = .message
          .attributes.remote_addr = parsed.remote_addr
          .attributes.request_method = parsed.request_method
          .attributes.request_uri = parsed.request_uri
          .attributes.status = parsed.status
          .attributes.body_bytes_sent = parsed.body_bytes_sent
          .attributes.http_referer = parsed.http_referer
          .attributes.http_user_agent = parsed.http_user_agent
          .attributes.request_time = parsed.request_time
          .attributes.service = "mltru-com"
          del(.message)

    sinks:
      openobserve:
        type: opentelemetry
        inputs: ["parse_json"]
        endpoint: http://o2c-openobserve-collector-gateway-collector.openobserve-collector:4318
